#!/usr/bin/env python3
"""Tables and figure for the shortlist diagnostics and calibration analysis.

Source: ``results/derived/R203_shortlist_diagnostics/summary.json`` produced by
``scripts/analyze_shortlist_diagnostics.py``.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "paper" / "figures"))
from figures4papers_style import (  # noqa: E402
    FigureStyle,
    PALETTE,
    apply_publication_style,
    create_subplots,
    finalize_figure,
    make_trend,
)

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "results/derived/R203_shortlist_diagnostics/summary.json"
TABLE_DIR = ROOT / "paper/tables"
FIGURE_DIR = ROOT / "paper/figures"
DATASETS = ["METRLA", "PEMSBAY", "PEMS03", "PEMS04", "PEMS07", "PEMS08"]
LABELS = {
    "METRLA": "METR-LA",
    "PEMSBAY": "PEMS-BAY",
    "PEMS03": "PEMS03",
    "PEMS04": "PEMS04",
    "PEMS07": "PEMS07",
    "PEMS08": "PEMS08",
}
Q_VALUES = ("1", "2", "4", "8", "16")
HEADER = "% Generated by scripts/build_shortlist_tables.py -- do not edit by hand.\n"


def fmt(value: float, digits: int = 4) -> str:
    text = f"{value:.{digits}f}"
    if text.startswith("-0"):
        return "-" + text[2:]
    if text.startswith("0"):
        return text[1:]
    return text


def write(name: str, body: str) -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    (TABLE_DIR / name).write_text(HEADER + body, encoding="utf-8")


def table_decomposition(summary: dict) -> None:
    rows = []
    for dataset in DATASETS:
        if dataset not in summary["datasets"]:
            continue
        d = summary["datasets"][dataset]["decomposition"]
        share = d["screening"]["mean"] / d["total"]["mean"] if d["total"]["mean"] > 0 else float("nan")
        rows.append(
            "{} & {} & {} & {} & {} \\\\".format(
                LABELS[dataset],
                fmt(d["screening"]["mean"]),
                fmt(d["reranking"]["mean"]),
                fmt(d["total"]["mean"]),
                fmt(share, 2),
            )
        )
    body = "\n".join(
        [
            "% source: results/derived/R203_shortlist_diagnostics/summary.json (decomposition)",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{One-step routing regret decomposed into the screening and reranking",
            "terms of Eq.~\\eqref{eq:decomposition}, in true marginal-utility units, at the",
            "deployed shortlist size $q=4$. The final column is the screening share.}",
            "\\label{tab:decomposition}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrr}",
            "\\toprule",
            "Dataset & Screening & Reranking & Total & Screening share\\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    write("tab_decomposition.tex", body)


def table_screening(summary: dict) -> None:
    rows = []
    for dataset in DATASETS:
        if dataset not in summary["datasets"]:
            continue
        screening = summary["datasets"][dataset]["screening"]
        cells = [f"{screening[q]['recall']:.2f} / {fmt(screening[q]['mean_regret'], 3)}" for q in Q_VALUES]
        rows.append(f"{LABELS[dataset]} & " + " & ".join(cells) + " \\\\")
    body = "\n".join(
        [
            "% source: results/derived/R203_shortlist_diagnostics/summary.json (screening)",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{Cached screening as a function of the shortlist size. Each cell reports",
            "the recall of the truly best candidate and the mean screening regret in true",
            "marginal-utility units.}",
            "\\label{tab:screening}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrrr}",
            "\\toprule",
            "Dataset & $q=1$ & $q=2$ & $q=4$ & $q=8$ & $q=16$\\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    write("tab_screening.tex", body)


def table_calibration(summary: dict) -> None:
    thresholds = list(next(iter(summary["datasets"].values()))["threshold_sweep"].keys())
    rows = []
    for threshold in thresholds:
        gain = np.mean([summary["datasets"][d]["threshold_sweep"][threshold]["mean_gain"] for d in DATASETS])
        harm = np.mean(
            [summary["datasets"][d]["threshold_sweep"][threshold]["negative_transfer_rate"] for d in DATASETS]
        )
        contexts = np.mean([summary["datasets"][d]["threshold_sweep"][threshold]["mean_contexts"] for d in DATASETS])
        coverage = np.mean([summary["datasets"][d]["threshold_sweep"][threshold]["coverage"] for d in DATASETS])
        rows.append(
            "{} & {} & {} & {:.2f} & {:.2f} \\\\".format(
                threshold, fmt(gain), fmt(harm, 3), contexts, coverage
            )
        )
    precision = np.mean([summary["datasets"][d]["calibration"]["precision"] for d in DATASETS])
    recall = np.mean([summary["datasets"][d]["calibration"]["recall"] for d in DATASETS])
    caption = (
        "\\caption{Stopping threshold sweep, averaged over the six datasets. Raising the "
        "threshold on the estimated marginal utility trades gain for a lower "
        "negative-transfer rate and fewer contexts. Coverage is the fraction of "
        "episodes on which the router selects at least one context. At the deployed "
        "threshold of zero the positive-utility decision has precision "
        f"{precision:.2f} and recall {recall:.2f}, where precision is the fraction of "
        "selected candidates with positive true marginal utility and recall is the "
        "fraction of positive-utility candidates that are selected.}"
    )
    body = "\n".join(
        [
            "% source: results/derived/R203_shortlist_diagnostics/summary.json (threshold sweep)",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            caption,
            "\\label{tab:calibration}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrr}",
            "\\toprule",
            "Threshold $\\tau$ & Mean gain & Neg. transfer & Contexts & Coverage\\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    write("tab_calibration.tex", body)


def figure_diagnostics(summary: dict) -> None:
    apply_publication_style(FigureStyle(font_size=7.0, axes_linewidth=1.2))
    fig, axes = create_subplots(
        1, 3, figsize=(5.6, 2.15), gridspec_kw={"width_ratios": [1.0, 1.05, 1.0], "wspace": 0.42}
    )
    ax_a, ax_b, ax_c = axes

    qs = np.asarray([int(q) for q in Q_VALUES], dtype=float)
    recall = np.asarray(
        [np.mean([summary["datasets"][d]["screening"][q]["recall"] for d in DATASETS]) for q in Q_VALUES]
    )
    regret = np.asarray(
        [np.mean([summary["datasets"][d]["screening"][q]["mean_regret"] for d in DATASETS]) for q in Q_VALUES]
    )
    make_trend(
        ax_a,
        qs,
        [recall],
        labels=["Recall (left)"],
        ylabel="Recall of the best candidate",
        xlabel="Shortlist size $q$",
        colors=[PALETTE["blue_main"]],
        linewidth=1.8,
        markersize=3.6,
    )
    ax_a.set_xticks(qs)
    ax_a.set_xticklabels([str(int(q)) for q in qs])
    ax_a.set_ylim(0, 1.08)
    ax_a2 = ax_a.twinx()
    make_trend(
        ax_a2,
        qs,
        [regret],
        labels=["Screening regret (right)"],
        colors=[PALETTE["red_strong"]],
        linewidth=1.4,
        marker="s",
        markersize=3.0,
        show_shadow=False,
    )
    ax_a2.set_yticks([0.0, 0.04])
    ax_a2.set_yticklabels(["0", ".04"], fontsize=5.8)
    ax_b.tick_params(axis="y", labelsize=5.8)
    ax_a2.spines["top"].set_visible(False)
    handles = ax_a.get_legend_handles_labels()[0] + ax_a2.get_legend_handles_labels()[0]
    ax_a.legend(handles, ["Recall (left)", "Screening regret (right)"], frameon=False,
                loc="upper center", fontsize=5.4, handlelength=1.2, labelspacing=0.2)

    screening = np.asarray([summary["datasets"][d]["decomposition"]["screening"]["mean"] for d in DATASETS])
    reranking = np.asarray([summary["datasets"][d]["decomposition"]["reranking"]["mean"] for d in DATASETS])
    positions = np.arange(len(DATASETS))
    ax_b.bar(positions - 0.19, screening, width=0.36, color=PALETTE["red_strong"], edgecolor="black",
             linewidth=0.7, label="Screening")
    ax_b.bar(positions + 0.19, reranking, width=0.36, color=PALETTE["blue_main"], edgecolor="black",
             linewidth=0.7, label="Reranking")
    ax_b.set_xticks(positions)
    ax_b.set_xticklabels([LABELS[d] for d in DATASETS], rotation=35, ha="right", fontsize=5.6)
    ax_b.legend(frameon=False, loc="upper right", fontsize=5.8)

    thresholds = np.asarray(
        [float(t) for t in next(iter(summary["datasets"].values()))["threshold_sweep"]]
    )
    gains = np.asarray(
        [
            np.mean([summary["datasets"][d]["threshold_sweep"][f"{t:.2f}"]["mean_gain"] for d in DATASETS])
            for t in thresholds
        ]
    )
    harms = np.asarray(
        [
            np.mean(
                [summary["datasets"][d]["threshold_sweep"][f"{t:.2f}"]["negative_transfer_rate"] for d in DATASETS]
            )
            for t in thresholds
        ]
    )
    make_trend(
        ax_c,
        harms,
        [gains],
        ylabel="Mean gain",
        xlabel="Negative-transfer rate",
        colors=[PALETTE["green_3"]],
        linewidth=1.6,
        markersize=3.4,
        show_shadow=False,
    )
    for index, tau in enumerate(thresholds):
        if tau in (0.0, 0.3):
            ax_c.annotate(
                f"$\\tau={tau:g}$",
                (harms[index], gains[index]),
                textcoords="offset points",
                xytext=(3, -7),
                fontsize=5.6,
                color="#4D4D4D",
            )

    finalize_figure(fig, FIGURE_DIR / "fig5_diagnostics", formats=("pdf", "png"), dpi=300, pad=0.10)


def main() -> None:
    summary = json.loads(SOURCE.read_text(encoding="utf-8"))
    table_decomposition(summary)
    table_screening(summary)
    table_calibration(summary)
    figure_diagnostics(summary)
    print(f"wrote shortlist tables to {TABLE_DIR} and fig5_diagnostics to {FIGURE_DIR}")


if __name__ == "__main__":
    main()
