#!/usr/bin/env python3
"""Controlled harm ladder for the risk-controlled selective routing study.

Source: ``results/raw/R200_harm_ladder_*`` (five seeds per harmful fraction,
per-state diagnostics saved). Emits the table used by ``paper_risk``.
"""

from __future__ import annotations

import csv
import glob
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper_risk/tables/tab_harm_ladder.tex"
POLICIES = ["mur_interval", "mur_free_threshold", "mur_light", "static_utility", "oracle"]


def fmt(value: float, digits: int = 4) -> str:
    text = f"{value:.{digits}f}"
    if text.startswith("-0"):
        return "-" + text[2:]
    if text.startswith("0"):
        return text[1:]
    return text


def main() -> None:
    files = sorted(glob.glob(str(ROOT / "results/raw/R200_harm_ladder_*/h*/result.json")))
    if not files:
        raise SystemExit("no harm-ladder runs found")
    rows = []
    for path in files:
        record = json.loads(Path(path).read_text(encoding="utf-8"))
        rows.append(
            (
                float(record["config"]["harmful_fraction"]),
                int(record["config"]["seed"]),
                record["metrics"],
            )
        )
    fractions = sorted({row[0] for row in rows})
    lines = []
    detail = []
    for fraction in fractions:
        subset = [row for row in rows if abs(row[0] - fraction) < 1e-9]

        def mean(policy: str, metric: str) -> float:
            return float(np.mean([row[2][policy][metric] for row in subset]))

        lines.append(
            "{} & {} & {} & {:.1f} & {} & {} & {} & {} \\\\".format(
                f"{fraction:g}",
                fmt(mean("mur_interval", "mean_prediction_gain")),
                fmt(mean("mur_interval", "negative_transfer_rate")),
                mean("mur_interval", "mean_selected_contexts"),
                fmt(mean("mur_light", "mean_prediction_gain")),
                fmt(mean("mur_light", "negative_transfer_rate")),
                fmt(mean("static_utility", "mean_prediction_gain")),
                fmt(mean("oracle", "mean_prediction_gain")),
            )
        )
        detail.append(
            {
                "harmful_fraction": fraction,
                "seeds": len(subset),
                "calibrated_gain": mean("mur_interval", "mean_prediction_gain"),
                "calibrated_harm": mean("mur_interval", "negative_transfer_rate"),
                "calibrated_contexts": mean("mur_interval", "mean_selected_contexts"),
                "uncalibrated_gain": mean("mur_light", "mean_prediction_gain"),
                "uncalibrated_harm": mean("mur_light", "negative_transfer_rate"),
                "static_gain": mean("static_utility", "mean_prediction_gain"),
                "static_harm": mean("static_utility", "negative_transfer_rate"),
                "oracle_gain": mean("oracle", "mean_prediction_gain"),
                "headroom": float(np.mean([row[2]["state_conditioning_headroom"] for row in subset])),
            }
        )
    body = "\n".join(
        [
            "% Generated by scripts/build_risk_harm_ladder.py -- do not edit by hand.",
            "% source: results/raw/R200_harm_ladder_*/h*/result.json",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{Controlled harm ladder over five runs per harmful fraction. The",
            "calibrated gate uses the split-conformal lower bound at level $.05$; the",
            "uncalibrated router acts whenever the estimated utility is positive. Gains are",
            "loss reductions relative to the anchor-only predictor.}",
            "\\label{tab:harm-ladder}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrrrrr}",
            "\\toprule",
            "Harmful fraction & Cal. gain & Cal. harm & Cal. contexts & Uncal. gain & Uncal. harm & Static gain & Oracle gain\\\\",
            "\\midrule",
            *lines,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    derived = ROOT / "results/derived/R204_harm_ladder_summary"
    derived.mkdir(parents=True, exist_ok=True)
    (derived / "summary.json").write_text(
        json.dumps({"source": files, "rows": detail}, indent=2) + "\n", encoding="utf-8"
    )
    print(f"wrote {OUT} and {derived / 'summary.json'}")
    for entry in detail:
        print(
            f"harm={entry['harmful_fraction']:.2f}: calibrated gain {entry['calibrated_gain']:.4f} "
            f"harm {entry['calibrated_harm']:.4f} | uncalibrated gain {entry['uncalibrated_gain']:.4f} "
            f"harm {entry['uncalibrated_harm']:.4f} | headroom {entry['headroom']:.4f}"
        )


if __name__ == "__main__":
    main()
