#!/usr/bin/env python3
"""Baseline comparison matrix for the manuscript.

Reads the deployable-policy matrix produced by ``build_kbs_result_tables.py``
and combines it with the properties and provenance of each policy, so that the
comparison table cannot drift from the reported numbers.

Output: ``refine-logs/BASELINE_MATRIX.md``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLE = ROOT / "paper/tables/tab_deployable.tex"
OUT = ROOT / "refine-logs/BASELINE_MATRIX.md"

DATASETS = ["METR-LA", "PEMS-BAY", "PEMS03", "PEMS04", "PEMS07", "PEMS08"]

# Policy -> (family, set-conditioned, uses predictor response, trained,
#            reference key, short reference, venue)
PROPERTIES = {
    "Relevance": (
        "content similarity", "no", "no", "no", "—",
        "similarity-based selection family", "—",
    ),
    "MMR": (
        "content diversity", "no", "no", "no", "carbonell1998use",
        "The use of MMR, diversity-based reranking for reordering documents and producing summaries",
        "SIGIR 1998",
    ),
    "Standalone Utility": (
        "learned outcome utility", "no", "no", "router training", "hashimoto-etal-2024-take",
        "Take One Step at a Time to Know Incremental Utility of Demonstration",
        "NAACL 2024",
    ),
    "Cached-only router": (
        "learned, cached state", "yes", "no", "router training", "—",
        "ablation of the proposed router", "—",
    ),
    "R-MUR": (
        "learned, response-aware", "yes", "yes", "router training", "—",
        "this paper", "—",
    ),
    "Response-aware one-shot": (
        "learned, response, one shot", "empty only", "yes", "router training", "—",
        "ablation of the proposed router: same scorer, no sequential update", "—",
    ),
    "Facility location": (
        "submodular coverage", "no", "no", "no", "lin2011class",
        "A Class of Submodular Functions for Document Summarization",
        "ACL 2011",
    ),
    "Facility location + relevance": (
        "submodular coverage", "no", "no", "no", "lin2011class",
        "weighted variant of the same objective", "ACL 2011",
    ),
    "DPP greedy": (
        "determinantal diversity", "no", "no", "no", "kulesza2012determinantal",
        "Determinantal Point Processes for Machine Learning",
        "FnT Machine Learning 2012",
    ),
    "k-center": (
        "farthest-point clustering", "no", "no", "no", "—",
        "classical k-center greedy rule", "—",
    ),
    "Greedy validation set": (
        "fixed set, validation", "no", "no", "predictor on validation", "zhu2025best",
        "Best Subset Selection: Optimal Pursuit for Feature Selection and Elimination",
        "ICML 2025",
    ),
    "Adaptive-$k$ relevance": (
        "fixed set, variable size", "no", "no", "predictor on validation", "taguchi2025adaptive",
        "Efficient Context Selection for Long-Context QA: Adaptive-$k$",
        "EMNLP 2025",
    ),
    "Cluster-based selection": (
        "fixed set, clustering", "no", "no", "no", "qin2023iterative",
        "In-Context Learning with Iterative Demonstration Selection",
        "arXiv:2310.09881",
    ),
    "Two-step lookahead set": (
        "fixed set, non-greedy", "no", "no", "predictor on validation",
        "valancius2023acquisition",
        "Acquisition Conditioned Oracle for Nongreedy Active Feature Acquisition",
        "arXiv:2302.13960 (with ICML 2025 for stochastic encodings)",
    ),
    "Gradient influence": (
        "fixed set, first order", "no", "no", "predictor on validation", "zhang2025linear",
        "Linear-Time Demonstration Selection for In-Context Learning via Gradient Estimation",
        "EMNLP 2025",
    ),
}


def parse_table() -> dict[str, dict[str, float]]:
    rows: dict[str, dict[str, float]] = {}
    for line in TABLE.read_text(encoding="utf-8").splitlines():
        match = re.match(r"^([A-Za-z].*?) & (.*?)\\\\\s*$", line)
        if not match:
            continue
        label = match.group(1).strip()
        if label == "Method":
            continue
        cells = [cell.strip() for cell in match.group(2).split(" & ")]
        if len(cells) != 8:
            continue
        values = {}
        for name, cell in zip(DATASETS + ["rank", "harm"], cells):
            if name == "rank":
                values[name] = float(cell)
            else:
                text = cell if cell.startswith("-") else cell.lstrip("0")
                values[name] = float(text) if text not in ("", "-") else float("nan")
        rows[label] = values
    return rows


def main() -> None:
    rows = parse_table()
    lines = [
        "# Baseline comparison matrix",
        "",
        "Generated by `scripts/build_baseline_matrix.py` from",
        "`paper/tables/tab_deployable.tex`, which in turn is built from the run",
        "sets `R080b` (learned policies), `R202` (content-based subset rules) and",
        "`R206` (fixed-set acquisition rules). Values are prediction gains",
        "averaged over 32 fixed targets per dataset and three independent runs;",
        "the harm rate is the per-episode negative-transfer rate. *Response at test*",
        "records whether the policy evaluates the frozen predictor while it selects on",
        "a test episode; *offline tuning* records what it is allowed to use before",
        "that, where the validation-based rules do use the predictor on held-out",
        "episodes.",
        "",
        "| Policy | Family | Set-cond. | Response at test | Offline tuning | Reference | Venue | "
        + " | ".join(DATASETS)
        + " | Avg. rank | Harm |",
        "|---|---|:--:|:--:|:--:|---|--|"
        + " | ".join("--:" for _ in DATASETS)
        + " | --: | --:|",
    ]
    for label, values in rows.items():
        if label not in PROPERTIES:
            continue
        family, set_cond, response, trained, _key, reference, venue = PROPERTIES[label]
        cells = " | ".join(f"{values[d]:+.4f}" for d in DATASETS)
        lines.append(
            f"| **{label}** | {family} | {set_cond} | {response} | {trained} | "
            f"{reference} | {venue} | {cells} | {values['rank']:.2f} | {values['harm']:.4f} |"
        )

    unlisted = [label for label in PROPERTIES if label not in rows]
    if unlisted:
        lines += ["", f"Policies missing from the table: {', '.join(unlisted)}"]

    lines += [
        "",
        "## Reference points (not deployable)",
        "",
        "| Policy | Definition | Role |",
        "|---|---|---|",
        "| Standalone oracle | ranks candidates by the true standalone marginal $u(j\\mid\\emptyset)$ | reference for the value of the first selection |",
        "| Sequential oracle | recomputes the true marginal after every selection | upper bound on state-conditioned selection |",
        "",
        "## Coverage of the design space",
        "",
        "| Design decision | Policies that isolate it |",
        "|---|---|",
        "| informative content (similarity) | Relevance |",
        "| diversity | MMR, DPP greedy |",
        "| coverage | Facility location, Facility location + relevance |",
        "| clustering | k-center, Cluster-based selection |",
        "| standalone outcome value | Standalone Utility |",
        "| state conditioning without the response | Cached-only router |",
        "| offline tuned set (no per-episode decision) | Greedy validation set, Adaptive-$k$, Two-step lookahead, Gradient influence |",
        "| state conditioning with the response | R-MUR |",
        "",
        "## Gaps",
        "",
        "- `k-center` and `Relevance` have no dedicated single reference in the",
        "  bibliography; they are reported as classical rules of their families.",
        "- `Cluster-based selection` and `Two-step lookahead set` are cited to",
        "  arXiv records because the retrieved metadata did not state a venue.",
        "- RankRAG, GenICL, Learning to Cut and Dynamic Feature Graph are cited for",
        "  positioning only; they are not implemented as baselines.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} with {len(rows)} policies")


if __name__ == "__main__":
    main()
