#!/usr/bin/env python3
"""Generate the result tables of the risk-controlled manuscript.

Source: ``results/derived/R200_risk_control/summary.json``, produced by
``scripts/analyze_risk_control.py`` from the saved deployment-state traces of
the multi-target runs (and, once available, the controlled harm ladder).
"""

from __future__ import annotations

import numpy as np

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "results/derived/R200_risk_control/summary.json"
OUT_DIR = ROOT / "paper_risk/tables"
LABELS = {
    "METRLA": "METR-LA",
    "PEMSBAY": "PEMS-BAY",
    "PEMS03": "PEMS03",
    "PEMS04": "PEMS04",
    "PEMS07": "PEMS07",
    "PEMS08": "PEMS08",
}
LEVELS = ("0.005", "0.010", "0.020", "0.050")
HEADER = "% Generated by scripts/build_risk_tables.py -- do not edit by hand.\n"


def fmt(value: float, digits: int = 4) -> str:
    if value is None:
        return "n/a"
    text = f"{value:.{digits}f}"
    if text.startswith("-0"):
        text = "-" + text[2:]
    elif text.startswith("0"):
        text = text[1:]
    return text


def write(name: str, body: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / name).write_text(HEADER + body, encoding="utf-8")


def table_budget(summary: dict) -> None:
    p5 = summary["protocols"]["P5_conformal_risk_control"]
    header = "Dataset & " + " & ".join(f"$\\alpha={float(a):g}$" for a in LEVELS) + " \\\\"
    rows = []
    for dataset, entry in p5.items():
        cells = []
        for alpha in LEVELS:
            level = entry[f"alpha_{alpha}"]["global"]
            cells.append(f"{fmt(level['harm_mass'])} / {fmt(level['selected_fraction'], 3)}")
        rows.append(f"{LABELS.get(dataset, dataset)} & " + " & ".join(cells) + " \\\\")
    body = "\n".join(
        [
            "% source: results/derived/R200_risk_control/summary.json (P5)",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{Risk-controlled gate on deployment states. Each cell reports the",
            "realised harmful-selection mass and the retained fraction of decisions",
            "(coverage) at the nominal budget $\\alpha$. The threshold is calibrated on",
            "half of the target sensors and evaluated on the other half.}",
            "\\label{tab:budget}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrr}",
            "\\toprule",
            header,
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    write("tab_budget.tex", body)


def table_certification(summary: dict) -> None:
    p5 = summary["protocols"]["P5_conformal_risk_control"]
    rows = []
    for dataset, entry in p5.items():
        level = entry["alpha_0.020"]
        interval = level["interval_lcb"]
        budget = level["global"]
        ratio = (
            budget["selected_fraction"] / interval["selected_fraction"]
            if interval["selected_fraction"] > 0
            else float("inf")
        )
        rows.append(
            "{} & {} & {} & {} & {} & {:.1f}$\\times$ \\\\".format(
                LABELS.get(dataset, dataset),
                fmt(interval["selected_fraction"], 3),
                fmt(budget["selected_fraction"], 3),
                fmt(budget["harm_mass"]),
                fmt(budget["gain"]),
                ratio,
            )
        )
    body = "\n".join(
        [
            "% source: results/derived/R200_risk_control/summary.json (P5, alpha = .02)",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{Interval certification against budget control at the same nominal",
            "level $\\alpha=.02$. The interval gate accepts a decision only when the",
            "conformal lower bound is positive; the budget gate accepts when the score",
            "reaches the calibrated threshold. The last column is the coverage ratio of",
            "budget control to interval certification.}",
            "\\label{tab:certification}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrrr}",
            "\\toprule",
            "Dataset & Interval coverage & Budget coverage & Harm mass & Gain & Ratio\\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    write("tab_certification.tex", body)


def table_transfer(summary: dict) -> None:
    p6 = summary["protocols"]["P6_cross_dataset_threshold"]
    rows = []
    for dataset, entry in p6.items():
        level = entry["alpha_0.020"]
        rows.append(
            "{} & {} & {} & {} & {} \\\\".format(
                LABELS.get(dataset, dataset),
                fmt(level["threshold"], 3),
                fmt(level["harm_mass"]),
                fmt(level["selected_fraction"], 3),
                fmt(level["selective_risk"], 3),
            )
        )
    body = "\n".join(
        [
            "% source: results/derived/R200_risk_control/summary.json (P6)",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{Threshold transfer. The threshold is calibrated on every other",
            "dataset at $\\alpha=.02$ and evaluated on the held-out dataset. Realised harm",
            "stays close to the nominal budget, and the last column reports the harmful",
            "share among accepted decisions.}",
            "\\label{tab:transfer}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrr}",
            "\\toprule",
            "Held-out dataset & Threshold & Harm mass & Coverage & Harmful share\\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    write("tab_transfer.tex", body)


def table_frontier(summary: dict) -> None:
    p7 = summary["protocols"]["P7_share_vs_mass"]
    coverages = ("0.02", "0.05", "0.10", "0.20", "0.30", "0.50", "1.00")
    header = "Dataset & " + " & ".join(f"{float(c):.2f}" for c in coverages) + " \\\\"
    rows = []
    for dataset, entry in p7.items():
        cells = [fmt(entry["risk_coverage"][c], 3) for c in coverages]
        rows.append(f"{LABELS.get(dataset, dataset)} & " + " & ".join(cells) + " \\\\")
    mean_cells = [
        fmt(float(np.mean([entry["risk_coverage"][c] for entry in p7.values()])), 3) for c in coverages
    ]
    rows.append("\\midrule")
    rows.append("Mean & " + " & ".join(mean_cells) + " \\\\")
    body = "\n".join(
        [
            "% source: results/derived/R200_risk_control/summary.json (P7)",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{Risk--coverage frontier of the response-aware score. Each entry is the",
            "smallest harmful share that any threshold on this score can achieve at the",
            "stated coverage, computed on the evaluation targets. The frontier bounds every",
            "threshold rule, including the calibrated gate.}",
            "\\label{tab:frontier}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrrrrr}",
            "\\toprule",
            "Dataset & " + " & ".join(f"{float(c):.2f}" for c in coverages) + "\\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    write("tab_frontier.tex", body)


def table_operating_points(summary: dict) -> None:
    p5 = summary["protocols"]["P5_conformal_risk_control"]
    rows = []
    for dataset, entry in p5.items():
        level = entry["alpha_0.020"]
        budget = level["global"]
        interval = level["interval_lcb"]
        sign = entry["uncalibrated"]
        always = entry.get("always_select", sign)
        rows.append(
            "{} & {} / {} & {} / {} & {} / {} & {} / {} & {} / {} \\\\".format(
                LABELS.get(dataset, dataset),
                fmt(always["selected_fraction"], 2),
                fmt(always["selective_risk"], 3),
                fmt(sign["selected_fraction"], 2),
                fmt(sign["selective_risk"], 3),
                fmt(interval["selected_fraction"], 3),
                fmt(interval["selective_risk"], 3),
                fmt(budget["selected_fraction"], 3),
                fmt(budget["selective_risk"], 3),
                fmt(budget["harm_mass"]),
                fmt(budget["gain"]),
            )
        )
    body = "\n".join(
        [
            "% source: results/derived/R200_risk_control/summary.json (P5)",
            "\\begin{table}[t]",
            "\\centering",
            "\\small",
            "\\caption{Operating points. Each cell reports coverage and the harmful share",
            "among accepted decisions. The budget gate is calibrated at $\\alpha=.02$; the",
            "final column reports its harmful-selection mass and the mean true utility of",
            "its accepted selections.}",
            "\\label{tab:objectives}",
            "\\resizebox{\\linewidth}{!}{%",
            "\\begin{tabular}{lrrrrr}",
            "\\toprule",
            "Dataset & Always & Sign gate & Interval gate & Budget gate & Mass / gain\\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}}",
            "\\end{table}",
            "",
        ]
    )
    write("tab_objectives.tex", body)


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"missing {SOURCE}; run scripts/analyze_risk_control.py first")
    summary = json.loads(SOURCE.read_text(encoding="utf-8"))
    table_budget(summary)
    table_certification(summary)
    table_transfer(summary)
    table_frontier(summary)
    table_operating_points(summary)
    print(f"wrote risk tables to {OUT_DIR}")


if __name__ == "__main__":
    main()
